/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewIdRouteImport } from './routes/view.$id'
import { Route as ResourcesSecondaryRouteImport } from './routes/resources.secondary'
import { Route as ResourcesProgramsRouteImport } from './routes/resources.programs'
import { Route as ResourcesPrimaryRouteImport } from './routes/resources.primary'
import { Route as ResourcesFormatsRouteImport } from './routes/resources.formats'
import { Route as ResourcesAdmissionsRouteImport } from './routes/resources.admissions'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIdRoute = ViewIdRouteImport.update({
  id: '/view/$id',
  path: '/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSecondaryRoute = ResourcesSecondaryRouteImport.update({
  id: '/secondary',
  path: '/secondary',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesProgramsRoute = ResourcesProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesPrimaryRoute = ResourcesPrimaryRouteImport.update({
  id: '/primary',
  path: '/primary',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesFormatsRoute = ResourcesFormatsRouteImport.update({
  id: '/formats',
  path: '/formats',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesAdmissionsRoute = ResourcesAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => ResourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/search': typeof SearchRoute
  '/resources/admissions': typeof ResourcesAdmissionsRoute
  '/resources/formats': typeof ResourcesFormatsRoute
  '/resources/primary': typeof ResourcesPrimaryRoute
  '/resources/programs': typeof ResourcesProgramsRoute
  '/resources/secondary': typeof ResourcesSecondaryRoute
  '/view/$id': typeof ViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/search': typeof SearchRoute
  '/resources/admissions': typeof ResourcesAdmissionsRoute
  '/resources/formats': typeof ResourcesFormatsRoute
  '/resources/primary': typeof ResourcesPrimaryRoute
  '/resources/programs': typeof ResourcesProgramsRoute
  '/resources/secondary': typeof ResourcesSecondaryRoute
  '/view/$id': typeof ViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/search': typeof SearchRoute
  '/resources/admissions': typeof ResourcesAdmissionsRoute
  '/resources/formats': typeof ResourcesFormatsRoute
  '/resources/primary': typeof ResourcesPrimaryRoute
  '/resources/programs': typeof ResourcesProgramsRoute
  '/resources/secondary': typeof ResourcesSecondaryRoute
  '/view/$id': typeof ViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/contribute'
    | '/resources'
    | '/search'
    | '/resources/admissions'
    | '/resources/formats'
    | '/resources/primary'
    | '/resources/programs'
    | '/resources/secondary'
    | '/view/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contribute'
    | '/resources'
    | '/search'
    | '/resources/admissions'
    | '/resources/formats'
    | '/resources/primary'
    | '/resources/programs'
    | '/resources/secondary'
    | '/view/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/contribute'
    | '/resources'
    | '/search'
    | '/resources/admissions'
    | '/resources/formats'
    | '/resources/primary'
    | '/resources/programs'
    | '/resources/secondary'
    | '/view/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ContributeRoute: typeof ContributeRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SearchRoute: typeof SearchRoute
  ViewIdRoute: typeof ViewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$id': {
      id: '/view/$id'
      path: '/view/$id'
      fullPath: '/view/$id'
      preLoaderRoute: typeof ViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/secondary': {
      id: '/resources/secondary'
      path: '/secondary'
      fullPath: '/resources/secondary'
      preLoaderRoute: typeof ResourcesSecondaryRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/programs': {
      id: '/resources/programs'
      path: '/programs'
      fullPath: '/resources/programs'
      preLoaderRoute: typeof ResourcesProgramsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/primary': {
      id: '/resources/primary'
      path: '/primary'
      fullPath: '/resources/primary'
      preLoaderRoute: typeof ResourcesPrimaryRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/formats': {
      id: '/resources/formats'
      path: '/formats'
      fullPath: '/resources/formats'
      preLoaderRoute: typeof ResourcesFormatsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/admissions': {
      id: '/resources/admissions'
      path: '/admissions'
      fullPath: '/resources/admissions'
      preLoaderRoute: typeof ResourcesAdmissionsRouteImport
      parentRoute: typeof ResourcesRoute
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesAdmissionsRoute: typeof ResourcesAdmissionsRoute
  ResourcesFormatsRoute: typeof ResourcesFormatsRoute
  ResourcesPrimaryRoute: typeof ResourcesPrimaryRoute
  ResourcesProgramsRoute: typeof ResourcesProgramsRoute
  ResourcesSecondaryRoute: typeof ResourcesSecondaryRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesAdmissionsRoute: ResourcesAdmissionsRoute,
  ResourcesFormatsRoute: ResourcesFormatsRoute,
  ResourcesPrimaryRoute: ResourcesPrimaryRoute,
  ResourcesProgramsRoute: ResourcesProgramsRoute,
  ResourcesSecondaryRoute: ResourcesSecondaryRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ContributeRoute: ContributeRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SearchRoute: SearchRoute,
  ViewIdRoute: ViewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
